defaults:
  - _self_
  - model: qwen25_3b_proj
  - dataset: protdt_420k
  - trainer: pt

# Project root directory (from train.py or relative path)
project_root: ${oc.env:PWD}

dataset:
  inference_mode: false

model:
  protein_config: ${project_root}/pretrained/ProTrek_650M/esm2_t33_650M_UR50D
  structure_config: ${project_root}/pretrained/ProTrek_650M/foldseek_t30_150M
  protrek_ckpt: ${project_root}/pretrained/ProTrek_650M/ProTrek_650M.pt
  prot_slot: 1
  stru_slot: 3
  proj_hid: 1024
  dropout: 0.1

# for deepspeed
local_rank: 0

trainer:
  logging_steps: 1
  save_steps: 200
  overwrite_output_dir: true
  save_only_model: false
  report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

  output_dir: null
  deepspeed: ${project_root}/ds_config/zero2.json
  gradient_checkpointing: true
  group_by_length: true

  ### train
  dataloader_num_workers: 8
  num_train_epochs: 1.0
  lr_scheduler_type: cosine
  bf16: true
  tf32: true
